version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/envguard-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Map host port 4200 to container port 4200
    restart: unless-stopped
    depends_on:
      - backend
      - pipeline

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    restart: unless-stopped
    environment:
      - DEBUG=True
    volumes:
      - ./backend:/app  # Mount the backend directory for development

  pipeline:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    restart: unless-stopped
    environment:
      - DEBUG=True
    volumes:
      - ./pipeline:/app  # Mount the pipeline directory for development

  docs:
    image: node:18  # Use Node.js image for http-server
    working_dir: /docs
    volumes:
      - ./docs:/docs  # Mount the docs directory
    command: >
      sh -c "npm install -g http-server && http-server --port 4201"
    ports:
      - "4201:4201"  # Map host port 4201 to container port 4201
    restart: unless-stopped
