version: "3.8"

services:
  frontend:
    image: abjpaul/robustify-design-frontend:latest
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - backend
      - pipeline
    environment:
      - HOST_ADDRESS=${HOST_ADDRESS:-localhost}
    command: >
      sh -c "echo $HOST_ADDRESS && node set-env.js && npm run start -- --host 0.0.0.0"

  backend:
    image: abjpaul/robustify-design-backend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - DEBUG=True
      - HOST_ADDRESS=${HOST_ADDRESS:-localhost}

  pipeline:
    image: abjpaul/robustify-design-pipeline:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DEBUG=True
      - HOST_ADDRESS=${HOST_ADDRESS:-localhost}

  docs:
    image: abjpaul/robustify-design-docs:latest
    ports:
      - "4201:4201"
    restart: unless-stopped
    environment:
      - HOST_ADDRESS=${HOST_ADDRESS:-localhost}